/* ============================================================
   catalogue.js — Source unique du catalogue produits GLOW UP
   Ajouter les produits ici directement.
   ============================================================ */

const CATALOGUE = [

  // ─── SÉRUM VITAMINE C ─────────────────────────────────────────
  {
    id: "m001",
    name: "Pure Vitamin C12 Sérum Anti-Âge",
    brand: "La Roche-Posay",
    category: "serum",
    imageUrl: "assets/vitamin-c12.jpg",
    amazonUrl: "https://amzn.to/4cwn1Xm",
    price: 50.00,
    rating: 4.6,
    reviews: 3000,
    description: "Sérum concentré 12% Vitamine C pure + Salicylate de Vitamine C. Illumine le teint, lisse les rides et améliore l'éclat de la peau.",
    skinTypeTags: [],
    routineStep: "serum",
    isFeatured: true,
    active: true
  },
  {
    id: "m007",
    name: "Revitalift Clinical Sérum 12% Vitamine C",
    brand: "L'Oréal Paris",
    category: "serum",
    imageUrl: "assets/loreal-revitalift-vitaminC.jpg",
    amazonUrl: "https://amzn.to/3OTH08B",
    price: 9.61,
    rating: 4.4,
    reviews: 15000,
    description: "Sérum antioxydant 12% Vitamine C Pure + Acide Salicylique + Vitamine E. Unifie le teint, réduit les pores et ridules. Flacon anti-UV pour préserver la Vitamine C.",
    skinTypeTags: [],
    routineStep: "serum",
    isFeatured: true,
    active: true
  },
  {
    id: "m008",
    name: "Sérum Booster d'Éclat Vitamine C Pure",
    brand: "Garnier Skin Active",
    category: "serum",
    imageUrl: "assets/garnier-vitaminC.jpg",
    amazonUrl: "https://amzn.to/4bbh1kh",
    price: 9.49,
    rating: 4.3,
    reviews: 9000,
    description: "Sérum éclat concentré en Vitamine C Pure + Acide Hyaluronique. Efface taches brunes, réduit les rides, illumine le teint en 1 semaine.",
    skinTypeTags: [],
    routineStep: "serum",
    isFeatured: false,
    active: true
  },
  {
    id: "m009",
    name: "The C-Boost Hero Sérum 15% Vitamine C",
    brand: "Yepoda",
    category: "serum",
    imageUrl: "assets/yepoda-vitaminC.jpg",
    amazonUrl: "https://amzn.to/47iKLuu",
    price: 29.00,
    rating: 4.6,
    reviews: 2200,
    description: "Sérum coréen concentré 15% Vitamine C + Acide Hyaluronique. Formule Slow Aging : illumine, repulpe et protège contre les radicaux libres. Vegan.",
    skinTypeTags: [],
    routineStep: "serum",
    isFeatured: false,
    active: true
  },

  // ─── NETTOYANT ────────────────────────────────────────────────
  {
    id: "m002",
    name: "Gel Nettoyant Apaisant Aloe Vera",
    brand: "Garnier Skin Active",
    category: "cleanser",
    imageUrl: "assets/Nettoyant-GARNIER2.jpg",
    amazonUrl: "https://amzn.to/4sS3l5h",
    price: 4.64,
    rating: 4.4,
    reviews: 8500,
    description: "Gel nettoyant à pH neutre enrichi en Aloe Vera, Glycérine et Acide Hyaluronique. Élimine maquillage et impuretés, hydrate et repulpe. Vegan & Cruelty Free.",
    skinTypeTags: ["normale", "mixte", "seche", "sensible"],
    routineStep: "cleanser",
    isFeatured: false,
    active: true
  },
  {
    id: "m003",
    name: "Gel Moussant Anti-Imperfections",
    brand: "CeraVe",
    category: "cleanser",
    imageUrl: "assets/Cerave-GelMoussantacnee.jpg",
    amazonUrl: "https://amzn.to/3PogVhX",
    price: 13.00,
    rating: 4.6,
    reviews: 12000,
    description: "Nettoyant purifiant à l'Acide Salicylique, Argile Blanche, Céramides et Niacinamide. Nettoie en douceur, réduit les imperfections. Idéal peaux acnéiques.",
    skinTypeTags: ["grasse", "mixte"],
    routineStep: "cleanser",
    isFeatured: true,
    active: true
  },
  {
    id: "m004",
    name: "Sebiaclear Gel Moussant Purifiant",
    brand: "SVR",
    category: "cleanser",
    imageUrl: "assets/SVR-Gelmoussantpeaumixte.jpg",
    amazonUrl: "https://amzn.to/4uhwFn4",
    price: 13.90,
    rating: 4.5,
    reviews: 5200,
    description: "Gel nettoyant anti-imperfections avec Gluconolactone 4% et Acide Salicylique 0,5%. Pour peaux mixtes à grasses et sensibles à tendance acnéique. 400 ml.",
    skinTypeTags: ["grasse", "mixte"],
    routineStep: "cleanser",
    isFeatured: false,
    active: true
  },
  {
    id: "m005",
    name: "Centella Cleansing Huile/Gel Démaquillant",
    brand: "Erborian",
    category: "cleanser",
    imageUrl: "assets/ERBORIAN-Gelnettoyant.jpg",
    amazonUrl: "https://amzn.to/47uYSgg",
    price: 22.43,
    rating: 4.5,
    reviews: 3100,
    description: "Huile/gel démaquillante à la Centella Asiatica. Se transforme en lait crémeux au contact de l'eau, élimine maquillage et impuretés en douceur. Cosmétique coréen.",
    skinTypeTags: ["normale", "mixte", "seche", "sensible"],
    routineStep: "cleanser",
    isFeatured: false,
    active: true
  },
  {
    id: "m006",
    name: "Heartleaf Nettoyant Moussant Doux Hydratant",
    brand: "ANUA",
    category: "cleanser",
    imageUrl: "assets/ANUA-laitnettoyant.jpg",
    amazonUrl: "https://amzn.to/4rZMAoH",
    price: 20.00,
    rating: 4.7,
    reviews: 4800,
    description: "Nettoyant moussant coréen ultra-doux avec Acide Hyaluronique, Glycérine, Zinc PCA et Panthénol. Nettoie sans agresser, maintient l'hydratation. 150 ml.",
    skinTypeTags: ["normale", "seche", "sensible"],
    routineStep: "cleanser",
    isFeatured: false,
    active: true
  },
  {
    id: "m042",
    name: "Baume Nettoyant Éclat au Son de Riz",
    brand: "Beauty of Joseon",
    category: "cleanser",
    imageUrl: "assets/Beautyofjoseon-baumenettoyant.jpg",
    amazonUrl: "https://amzn.to/4rlRQ4y",
    price: 17.98,
    rating: 4.6,
    reviews: 7200,
    description: "Baume démaquillant qui fond en huile au contact de la peau. Élimine maquillage, fond de teint et sébum en douceur. Son de riz + extraits de céréales : peau nourrie et hydratée après le lavage. Idéal peaux sèches. 100 ml.",
    skinTypeTags: ["seche", "normale", "sensible"],
    routineStep: "cleanser",
    isFeatured: false,
    active: true
  },
  {
    id: "m043",
    name: "Toleriane Fluide Dermo-Nettoyant Lait Démaquillant",
    brand: "La Roche-Posay",
    category: "cleanser",
    imageUrl: "assets/LAROCHEPOSAY-nettoyantlait.jpg",
    amazonUrl: "https://amzn.to/4bhLUnu",
    price: 16.60,
    rating: 4.6,
    reviews: 9400,
    description: "Lait démaquillant enrichi en Glycérine et Eau Thermale de La Roche-Posay. Nettoie visage et yeux sans parfum, sans rinçage. Formule apaisante testée dermatologiquement. Idéal pour les peaux sensibles, réactives et intolérantes.",
    skinTypeTags: ["sensible", "seche", "normale"],
    routineStep: "cleanser",
    isFeatured: false,
    active: true
  },
  {
    id: "m044",
    name: "Sebiaclear Gel Moussant Purifiant Anti-Imperfections 400ml",
    brand: "SVR",
    category: "cleanser",
    imageUrl: "assets/SVR-nettoyant.jpg",
    amazonUrl: "https://amzn.to/3NaueC8",
    price: 13.90,
    rating: 4.5,
    reviews: 5800,
    description: "Gel nettoyant purifiant grand format 400 ml. Gluconolactone 4% + Acide Salicylique 0,5% : nettoie en profondeur, resserre les pores et réduit les imperfections. Pour peaux mixtes à grasses, sensibles et à tendance acnéique.",
    skinTypeTags: ["grasse", "mixte"],
    routineStep: "cleanser",
    isFeatured: false,
    active: true
  },
  {
    id: "m045",
    name: "Sensifine Dermo-Nettoyant Apaisant",
    brand: "SVR",
    category: "cleanser",
    imageUrl: "assets/SVR-laitnettoyant.jpg",
    amazonUrl: "https://amzn.to/4cCYcJp",
    price: 14.39,
    rating: 4.5,
    reviews: 3600,
    description: "Nettoyant démaquillant apaisant à la Niacinamide et Propanediol. Élimine maquillage et impuretés sans agresser la peau. Formule ultra-douce pour peaux sensibles, réactives ou intolérantes. Sans rinçage. 200 ml.",
    skinTypeTags: ["sensible"],
    routineStep: "cleanser",
    isFeatured: false,
    active: true
  },
  {
    id: "m046",
    name: "Superfood Cleanser — Kale, Thé Vert & Épinards",
    brand: "Youth To The People",
    category: "cleanser",
    imageUrl: "assets/Youth To The People-nettoyant.jpg",
    amazonUrl: "https://amzn.to/3P1reZl",
    price: 15.90,
    rating: 4.5,
    reviews: 4200,
    description: "Nettoyant superaliment à pH équilibré enrichi en Chou Kale antioxydant, Thé Vert énergisant et Épinards détoxifiants. Démaquillant doux pour tous types de peau dont les peaux sensibles. Texture gel fraîche, sans sulfates agressifs.",
    skinTypeTags: [],
    routineStep: "cleanser",
    isFeatured: true,
    active: true
  },

  // ─── CONTOUR DES YEUX ─────────────────────────────────────────
  {
    id: "m010",
    name: "Revitalift Laser Eye Bag Instant Eraser",
    brand: "L'Oréal Paris",
    category: "eye",
    imageUrl: "assets/loreal-revitalift-contouryeux.jpg",
    amazonUrl: "https://amzn.to/4bhBNyR",
    price: 19.99,
    rating: 4.3,
    reviews: 6700,
    description: "Soin contour des yeux anti-âge qui réduit rides, poches, gonflements et perte de fermeté. Résultats visibles dès la première application. 15 ml.",
    skinTypeTags: [],
    routineStep: "eye",
    isFeatured: false,
    active: true
  },
  {
    id: "m011",
    name: "Under Eye Roller Caféine + Vitamine C",
    brand: "Wolf Project",
    category: "eye",
    imageUrl: "assets/Wolfproject-contourdesyeux-vitaminC.jpg",
    amazonUrl: "https://amzn.to/4rhUeJy",
    price: 16.99,
    rating: 4.5,
    reviews: 3400,
    description: "Rouleau énergisant sous les yeux avec Caféine, Vitamine C et Peptides. Réduit cernes et poches, lisse les ridules. Beauté coréenne, effet gel frais.",
    skinTypeTags: [],
    routineStep: "eye",
    isFeatured: false,
    active: true
  },
  {
    id: "m012",
    name: "Ginseng Power Eye Crème Anti-Âge",
    brand: "Erborian",
    category: "eye",
    imageUrl: "assets/ERBORIAN-Contourdesyeux.jpg",
    amazonUrl: "https://amzn.to/4cuHLPc",
    price: 27.98,
    rating: 4.5,
    reviews: 2100,
    description: "Crème contour des yeux lissante enrichie au Ginseng. Lutte contre les rides et ridules, raffermit et illumine le regard. Soin coréen de luxe. 15 ml.",
    skinTypeTags: [],
    routineStep: "eye",
    isFeatured: false,
    active: true
  },
  {
    id: "m013",
    name: "Revive Eye Sérum Contour Niacinamide + Rétinal",
    brand: "Beauty of Joseon",
    category: "eye",
    imageUrl: "assets/Beautyofjoseon-contourdesyeux.jpg",
    amazonUrl: "https://amzn.to/4rWsD1I",
    price: 15.79,
    rating: 4.6,
    reviews: 5600,
    description: "Sérum contour des yeux au Niacinamide et Rétinal. Corrige poches, ridules, cernes et rides. Formule coréenne légère, efficace dès 4 semaines. 30 ml.",
    skinTypeTags: [],
    routineStep: "eye",
    isFeatured: false,
    active: true
  },
  {
    id: "m014",
    name: "All About Eyes Crème Anti-Poches Anti-Cernes",
    brand: "Clinique",
    category: "eye",
    imageUrl: "assets/CLINIQUE-contourdesyeux.jpg",
    amazonUrl: "https://amzn.to/40eA08N",
    price: 31.99,
    rating: 4.4,
    reviews: 8900,
    description: "Crème yeux à l'Acide Hyaluronique, référence dermatologique. Réduit poches et cernes, hydrate intensément le contour des yeux. Allié maquillage. 15 ml.",
    skinTypeTags: [],
    routineStep: "eye",
    isFeatured: false,
    active: true
  },

  // ─── CRÈME HYDRATANTE JOUR ────────────────────────────────────
  {
    id: "m015",
    name: "Crème Hydratante Visage SPF30",
    brand: "CeraVe",
    category: "cream",
    imageUrl: "assets/Cerave-cremevisagejourspf30.jpg",
    amazonUrl: "https://amzn.to/4rYoevd",
    price: 12.65,
    rating: 4.5,
    reviews: 11000,
    description: "Crème de jour hydratante avec protection UVB+UVA SPF30. Acide Hyaluronique, Céramides, Niacinamide et Vitamine E. Non comédogène. Peaux normales à sèches. 52 ml.",
    skinTypeTags: ["normale", "seche"],
    routineStep: "moisturizer",
    isFeatured: false,
    active: true
  },
  {
    id: "m016",
    name: "Oat In Calming Gel Cream",
    brand: "PURITO",
    category: "cream",
    imageUrl: "assets/PURITO-crèmejour.jpg",
    amazonUrl: "https://amzn.to/4s074O7",
    price: 16.80,
    rating: 4.6,
    reviews: 4200,
    description: "Gel crème hydratant léger à l'extrait de graines d'Avoine. Non collant, non comédogène, sans parfum. Texture légère parfaite pour peaux sensibles. Skincare coréen. 100 ml.",
    skinTypeTags: ["sensible", "normale", "mixte"],
    routineStep: "moisturizer",
    isFeatured: false,
    active: true
  },
  {
    id: "m017",
    name: "The Day Light Crème Hydratante Purifiante",
    brand: "Yepoda",
    category: "cream",
    imageUrl: "assets/YEPODA-crèmejour.jpg",
    amazonUrl: "https://amzn.to/4uzZtHN",
    price: 26.00,
    rating: 4.5,
    reviews: 1800,
    description: "Crème de jour purifiante légère avec Eau de Rose, Armoise et Niacinamide. Sans huile, non obstruante. Teint unifié et peau nette. Skincare coréen vegan. 50 ml.",
    skinTypeTags: ["grasse", "mixte"],
    routineStep: "moisturizer",
    isFeatured: false,
    active: true
  },
  {
    id: "m018",
    name: "Collagène Triple + Acide Hyaluronique Crème",
    brand: "Medicube",
    category: "cream",
    imageUrl: "assets/MEDICUBE-crèmejour.jpg",
    amazonUrl: "https://amzn.to/4sDMPWp",
    price: 17.70,
    rating: 4.4,
    reviews: 2600,
    description: "Crème anti-rides coréenne au Triple Collagène, Acide Hyaluronique, Élastine Premium et Beurre de Karité. Repulpe, ferme et hydrate intensément. 50 ml.",
    skinTypeTags: ["normale", "seche"],
    routineStep: "moisturizer",
    isFeatured: false,
    active: true
  },
  {
    id: "m019",
    name: "Palpebral Baume Apaisant Réparateur",
    brand: "SVR",
    category: "cream",
    imageUrl: "assets/SVR-crèmejourpeauxsensibles.jpg",
    amazonUrl: "https://amzn.to/40lunFP",
    price: 17.79,
    rating: 4.6,
    reviews: 3900,
    description: "Baume apaisant et réparateur pour visage et contour des yeux secs et irrités. Acide Hyaluronique, Omégas 3-6-9 et Céramides AD. Peaux à tendance atopique. 30 ml.",
    skinTypeTags: ["seche", "sensible"],
    routineStep: "moisturizer",
    isFeatured: false,
    active: true
  },
  {
    id: "m020",
    name: "Toleriane Sensitive Crème Hydratante",
    brand: "La Roche-Posay",
    category: "cream",
    imageUrl: "assets/LAROCHEPOSAY-crèmevisagepeauxsensibles.jpg",
    amazonUrl: "https://amzn.to/4rYNaTm",
    price: 22.37,
    rating: 4.6,
    reviews: 14000,
    description: "Crème hydratante visage testée sur peaux sensibles. Glycérine, Céramide, Vitamine B3 et Eau Thermale. Hydrate, apaise et protège durablement. Recommandée par les dermatologues.",
    skinTypeTags: ["sensible", "normale"],
    routineStep: "moisturizer",
    isFeatured: false,
    active: true
  },
  {
    id: "m021",
    name: "Dynasty Cream Hydratante Peaux Sèches",
    brand: "Beauty of Joseon",
    category: "cream",
    imageUrl: "assets/BEAUTYOFJOSEON-crèmevisage.jpg",
    amazonUrl: "https://amzn.to/4uijMcs",
    price: 27.20,
    rating: 4.7,
    reviews: 7200,
    description: "Crème hydratante coréenne inspirée des rituels beauté traditionnels. Riche, nourrissante et réparatrice. Pour peaux sèches et sensibles. 100 ml.",
    skinTypeTags: ["seche", "sensible"],
    routineStep: "moisturizer",
    isFeatured: true,
    active: true
  },

  // ─── SPF ─────────────────────────────────────────────────────
  {
    id: "m022",
    name: "RESIST Anti-Âge Crème de Jour SPF30",
    brand: "Paula's Choice",
    category: "spf",
    imageUrl: "assets/PAULASCHOICE-crèmeSPF30peauxmixtes.jpg",
    amazonUrl: "https://amzn.to/4uhQPxh",
    price: 48.00,
    rating: 4.5,
    reviews: 3200,
    description: "Crème solaire visage anti-âge SPF30 matifiante avec antioxydants et Vitamine E. Protège contre UVA/UVB, réduit taches brunes et rides. Peaux mixtes à grasses. 60 ml.",
    skinTypeTags: ["grasse", "mixte"],
    routineStep: "spf",
    isFeatured: false,
    active: true
  },
  {
    id: "m023",
    name: "Advanced Sun Protection Crème Solaire SPF50",
    brand: "Paula's Choice",
    category: "spf",
    imageUrl: "assets/PAULASCHOICE-crèmeSPF50.jpg",
    amazonUrl: "https://amzn.to/47xxdLH",
    price: 48.00,
    rating: 4.5,
    reviews: 2800,
    description: "Crème solaire hydratante SPF50 PA++++. Filtres UVA et UVB larges + antioxydants anti-âge. Texture fondante non grasse. Peaux normales à sèches. 60 ml.",
    skinTypeTags: ["normale", "seche"],
    routineStep: "spf",
    isFeatured: false,
    active: true
  },
  {
    id: "m024",
    name: "Ultra Light Invisible Sunscreen SPF50",
    brand: "COSRX",
    category: "spf",
    imageUrl: "assets/COSRX-crèmeSPF50.jpg",
    amazonUrl: "https://amzn.to/4rWtAqN",
    price: 16.99,
    rating: 4.7,
    reviews: 9500,
    description: "Crème solaire invisible SPF50 PA++++ ultra-légère, absorption rapide, zéro effet blanc. Protection UV + boost hydratation. Texture aérienne. Skincare coréen.",
    skinTypeTags: ["normale", "grasse", "mixte"],
    routineStep: "spf",
    isFeatured: true,
    active: true
  },
  {
    id: "m025",
    name: "FotoUltra Age Repair Fusion Water SPF50",
    brand: "ISDIN",
    category: "spf",
    imageUrl: "assets/ISDIN-crèmeSPF50.jpg",
    amazonUrl: "https://amzn.to/4s03Zxr",
    price: 15.59,
    rating: 4.6,
    reviews: 6100,
    description: "Fluide solaire anti-âge SPF50 à texture eau. Fusion Water légère et non grasse. Protège, répare et prend soin de la peau au quotidien. Dermatologue recommandé.",
    skinTypeTags: [],
    routineStep: "spf",
    isFeatured: false,
    active: true
  },
  {
    id: "m026",
    name: "Uveblock Sun Serum SPF50 Effet Glow",
    brand: "Isispharma",
    category: "spf",
    imageUrl: "assets/ISISPHARMA-crèmeSPF50.jpg",
    amazonUrl: "https://amzn.to/4lhZvzG",
    price: 21.89,
    rating: 4.5,
    reviews: 2700,
    description: "Sérum solaire SPF50 avec effet glow lumineux. Hydrate 8h, protège et illumine. Texture fluide non grasse. Haute protection solaire. Conçu et fabriqué en France.",
    skinTypeTags: [],
    routineStep: "spf",
    isFeatured: false,
    active: true
  },

  // ─── BAUME À LÈVRES ────────────────────────────────────────────
  {
    id: "m027",
    name: "Ensemble de Baumes à Lèvres Biologiques (Pack de 6)",
    brand: "Sky Organics",
    category: "lipbalm",
    imageUrl: "assets/SKYORGANICS-BAUMEALEVRE.jpg",
    amazonUrl: "https://amzn.to/3NaTLLi",
    price: 14.24,
    rating: 4.5,
    reviews: 5200,
    description: "Pack de 6 baumes à lèvres biologiques certifiés. Cire d'abeille biologique, huiles et extraits botaniques précieux, Vitamine E nourrissante. Arômes 100% naturels. Idéal pour varier les saveurs selon l'humeur.",
    skinTypeTags: [],
    routineStep: "lipbalm",
    isFeatured: false,
    active: true
  },
  {
    id: "m028",
    name: "Baumes à Lèvres Cire d'Abeille & Vitamine E (Pack Duo)",
    brand: "Burt's Bees",
    category: "lipbalm",
    imageUrl: "assets/BURTSBEES-baumealevre.jpg",
    amazonUrl: "https://amzn.to/40k3xxK",
    price: 6.55,
    rating: 4.6,
    reviews: 28000,
    description: "La référence des baumes naturels — cire d'abeille pure et Vitamine E. Hydrate et protège intensément les lèvres sèches ou gercées. Sans parabènes ni phtalates. Pack duo économique (2 x 4,25 g).",
    skinTypeTags: [],
    routineStep: "lipbalm",
    isFeatured: false,
    active: true
  },
  {
    id: "m029",
    name: "Baume Apaisant Beurre de Cacao, Karité & Cire d'Abeille",
    brand: "Bees of Britain",
    category: "lipbalm",
    imageUrl: "assets/BEESOFBITAIN-baumealevres.jpg",
    amazonUrl: "https://amzn.to/4sxKdZN",
    price: 24.99,
    rating: 4.5,
    reviews: 1800,
    description: "Baume 100% pur et naturel au Beurre de Cacao (Theobroma Cacao), Karité (Butyrospermum Parkii) et Cire d'Abeille — triple action réparatrice. 100 ml grand format. 5% des bénéfices reversés à la protection des abeilles et pollinisateurs.",
    skinTypeTags: ["seche", "sensible"],
    routineStep: "lipbalm",
    isFeatured: false,
    active: true
  },
  {
    id: "m030",
    name: "Baume Lèvres Abîmées Ultra-Riche",
    brand: "Urgo",
    category: "lipbalm",
    imageUrl: "assets/URGO-baumealevres.jpg",
    amazonUrl: "https://amzn.to/4rXJO33",
    price: 8.37,
    rating: 4.4,
    reviews: 3600,
    description: "Formule dermato ultra-riche au Beurre de Karité et Miel purifié. Protège, répare et nourrit intensément les lèvres abîmées, gercées ou craquelées. Résultats visibles dès la première application. Tube 10 ml.",
    skinTypeTags: ["seche", "sensible"],
    routineStep: "lipbalm",
    isFeatured: false,
    active: true
  },
  {
    id: "m031",
    name: "Eight Hour Cream Baume Apaisant Réparateur Multi-Usage",
    brand: "Elizabeth Arden",
    category: "lipbalm",
    imageUrl: "assets/ELIZABETHARDEN-BAUMEALEVRES.jpg",
    amazonUrl: "https://amzn.to/3OZBcKI",
    price: 27.75,
    rating: 4.6,
    reviews: 12000,
    description: "Le baume iconique d'Elizabeth Arden depuis 1930 — multi-usage pour le visage, les lèvres, les coudes et les cuticules. Protège, répare et apaise en une seule application. Texture riche et enveloppante. Un classique de beauté intemporel.",
    skinTypeTags: ["seche", "sensible"],
    routineStep: "lipbalm",
    isFeatured: false,
    active: true
  },
  {
    id: "m032",
    name: "Eight Hour Cream Baume à Lèvres Hydratant SPF 15",
    brand: "Elizabeth Arden",
    category: "lipbalm",
    imageUrl: "assets/ELIZABETHARDEN-rougealevrebaume.jpg",
    amazonUrl: "https://amzn.to/40jbp2A",
    price: 22.94,
    rating: 4.5,
    reviews: 8400,
    description: "Soin lèvres multi-usage : hydrate, assouplit et protège avec SPF 15. Effet gloss lumineux non collant. Stick pratique format sac. Protège du froid, du vent et des UV — le must-have lèvres toutes saisons.",
    skinTypeTags: [],
    routineStep: "lipbalm",
    isFeatured: false,
    active: true
  },
  {
    id: "m033",
    name: "Cicavit+ Baume Lèvres Réparation Accélérée",
    brand: "SVR",
    category: "lipbalm",
    imageUrl: "assets/SVR-baumealevres.jpg",
    amazonUrl: "https://amzn.to/4rfaPhf",
    price: 7.27,
    rating: 4.7,
    reviews: 6800,
    description: "Baume protecteur réparation accélérée pour lèvres sèches, gercées et abîmées. 99% d'ingrédients d'origine naturelle. Sans parfum — idéal peaux sensibles et réactives. Formule cicatrisante cliniquement testée. 10 g.",
    skinTypeTags: ["sensible", "seche"],
    routineStep: "lipbalm",
    isFeatured: true,
    active: true
  },

  // ─── HYDRATATION H2O ──────────────────────────────────────────
  {
    id: "m034",
    name: "Sérum Rafraîchissant aux Algues — Contrôle Sébum",
    brand: "BIODANCE",
    category: "serum",
    imageUrl: "assets/BIODANCE-sérumpeauxmixtes.jpg",
    amazonUrl: "https://amzn.to/4ujtfA3",
    price: 21.25,
    rating: 4.5,
    reviews: 3200,
    description: "Sérum coréen aux algues marines : contrôle le sébum, resserre les pores et hydrate intensément. Texture eau ultra-légère. Idéal peaux grasses et mixtes qui manquent d'eau sans vouloir d'excès de gras.",
    skinTypeTags: ["grasse", "mixte"],
    routineStep: "serum",
    badge: "h2o",
    isFeatured: false,
    active: true
  },
  {
    id: "m035",
    name: "Sérum Hydratant Booster 1,5% Acide Hyaluronique Pur",
    brand: "Uriage",
    category: "serum",
    imageUrl: "assets/URIAGE-Eauthermale.jpg",
    amazonUrl: "https://amzn.to/3Np3az7",
    price: 23.49,
    rating: 4.6,
    reviews: 8700,
    description: "Booster hydratant à 1,5% d'Acide Hyaluronique Pur & Naturel enrichi en Eau Thermale d'Uriage. 86% de peaux repulpées dès l'application. Effet peau de pêche, texture fraîche et légère. Non comédogène. 30 ml.",
    skinTypeTags: [],
    routineStep: "serum",
    badge: "h2o",
    isFeatured: true,
    active: true
  },
  {
    id: "m036",
    name: "Ginseng Essence Water",
    brand: "Beauty of Joseon",
    category: "serum",
    imageUrl: "assets/Beautyofjoseon-Eaudessence.jpg",
    amazonUrl: "https://amzn.to/4um8YtE",
    price: 16.49,
    rating: 4.6,
    reviews: 14000,
    description: "Eau d'essence légendaire au Ginseng Rouge. Hydrate, unifie le teint et apaise les irritations grâce à l'allantoïne et au dipotassium glycyrrhizate. Sans ingrédients irritants. Certifiée GMP. Peaux sensibles bienvenues. 150 ml.",
    skinTypeTags: ["sensible"],
    routineStep: "serum",
    badge: "h2o",
    isFeatured: false,
    active: true
  },
  {
    id: "m037",
    name: "Crème Barrière Hydratante Apaisante aux Céramides & HA",
    brand: "Pyunkang Yul",
    category: "cream",
    imageUrl: "assets/PKY-Crèmehydratante.jpg",
    amazonUrl: "https://amzn.to/4scH7KY",
    price: 24.96,
    rating: 4.5,
    reviews: 4100,
    description: "Crème barrière coréenne : Centella Asiatica (apaisante), Extrait d'Arbre à Thé (anti-inflammatoire), Céramides (renforce la barrière) et Acide Hyaluronique 5 types (hydratation intense). Vegan. Idéale peaux sensibles réactives. 100 ml.",
    skinTypeTags: ["sensible", "seche"],
    routineStep: "moisturizer",
    badge: "h2o",
    isFeatured: false,
    active: true
  },
  {
    id: "m038",
    name: "Acide Hyaluronique 2% + B5 (à base de Céramides)",
    brand: "The Ordinary",
    category: "serum",
    imageUrl: "assets/THEORDINARY-H20.jpg",
    amazonUrl: "https://amzn.to/40iCD9A",
    price: 11.50,
    rating: 4.5,
    reviews: 22000,
    description: "Sérum hydratant en profondeur à l'Acide Hyaluronique pur + Vitamine B5 + Céramides. Repulpe, lisse et renforce la barrière hydrique. Texture légère, compatible tous types de peaux. Le rapport qualité-prix imbattable du skincare. 30 ml.",
    skinTypeTags: [],
    routineStep: "serum",
    badge: "h2o",
    isFeatured: true,
    active: true
  },
  {
    id: "m039",
    name: "Hyalu B5 Sérum Concentré Anti-Rides Repulpant",
    brand: "La Roche-Posay",
    category: "serum",
    imageUrl: "assets/LAROCHEPOSAY-H20.jpg",
    amazonUrl: "https://amzn.to/4lhZZWl",
    price: 42.00,
    rating: 4.6,
    reviews: 11000,
    description: "Sérum concentré anti-rides à l'Acide Hyaluronique, Vitamine B5 et Madecassoside. Répare la barrière cutanée, repulpe et lisse. Tous types de peaux dont les peaux sensibles. Dermatologiquement testé. 30 ml.",
    skinTypeTags: ["sensible"],
    routineStep: "serum",
    badge: "h2o",
    isFeatured: false,
    active: true
  },
  {
    id: "m040",
    name: "Snail Mucin 96% Power Repairing Essence Kit",
    brand: "COSRX",
    category: "serum",
    imageUrl: "assets/COSRX-H20.jpg",
    amazonUrl: "https://amzn.to/4sVRUtl",
    price: 31.20,
    rating: 4.7,
    reviews: 36000,
    description: "L'essence culte au filtrat de mucine d'escargot 96% — hydrate, répare et renforce la peau en profondeur. Booste l'absorption des autres soins. Texture aqueuse légère, non grasse. Coffret exclusif Amazon. Peau résiliente en 4 semaines.",
    skinTypeTags: [],
    routineStep: "serum",
    badge: "h2o",
    isFeatured: false,
    active: true
  },
  {
    id: "m041",
    name: "Hyaluronic Multi Peptide Serum",
    brand: "Medicube",
    category: "serum",
    imageUrl: "assets/MEDICUBE-H20.jpg",
    amazonUrl: "https://amzn.to/4bAc2Lq",
    price: 30.40,
    rating: 4.7,
    reviews: 5800,
    description: "Sérum prodige : 99% d'Acide Hyaluronique Haute Pureté + Peptides + PDRN. +39,9% d'hydratation en quelques secondes, maintenue 144h. Triple action repulpante sans résidu collant. Le best-seller hydratation de la K-beauty.",
    applyTip: "Matin et soir après le nettoyage. Déposer 3 à 4 gouttes sur les paumes, tapoter doucement sur tout le visage et le cou jusqu'à absorption complète avant d'appliquer la crème.",
    skinTypeTags: [],
    routineStep: "serum",
    badge: "h2o",
    isFeatured: true,
    active: true
  },

  // ─── MASQUE DE NUIT ───────────────────────────────────────────
  {
    id: "m047",
    name: "Wrapping Masque de Nuit Collagène Peel-Off",
    brand: "Medicube",
    category: "nightmask",
    imageUrl: "assets/MEDICUBE-crèmenuit.jpg",
    amazonUrl: "https://amzn.to/4llbe09",
    price: 12.82,
    rating: 4.5,
    reviews: 2900,
    description: "Masque de nuit peel-off au Collagène Hydrolysé. Forme un film occlusif qui booste l'élasticité et l'hydratation pendant le sommeil. Effet Glass Skin repulpant au réveil. Anti-relâchement et teint terne. Skincare coréenne. 75 ml.",
    applyTip: "En dernière étape de ta routine du soir, applique une couche généreuse sur le visage propre (évite le contour des yeux). Laisse agir toute la nuit. Le matin, décolle délicatement le film ou rince à l'eau tiède.",
    skinTypeTags: [],
    routineStep: "nightmask",
    isFeatured: false,
    active: true
  },
  {
    id: "m048",
    name: "Water Sleeping Mask",
    brand: "Laneige",
    category: "nightmask",
    imageUrl: "assets/LANEIGE-crèmenuit.jpg",
    amazonUrl: "https://amzn.to/40rh32G",
    price: 29.70,
    rating: 4.7,
    reviews: 18000,
    description: "Le masque de nuit culte de la K-beauty. Technology Moisture Wrap : enveloppe la peau d'une couche hydratante qui scelle les actifs et prévient l'évaporation pendant le sommeil. Extrait de fleurs de nuit + Acide Hyaluronique. Peau lisse et lumineuse au réveil. 70 ml.",
    applyTip: "En toute dernière étape du soir. Prendre l'équivalent d'une noisette avec la spatule, étaler uniformément sur le visage et le cou. Laisser agir toute la nuit. Rincer abondamment à l'eau tiède le matin.",
    skinTypeTags: [],
    routineStep: "nightmask",
    isFeatured: true,
    active: true
  },

  // ─── MEDICUBE — SÉRUMS & CONTOUR ──────────────────────────────
  {
    id: "m049",
    name: "Triple Collagen Serum 4.0",
    brand: "Medicube",
    category: "serum",
    imageUrl: "assets/MEDICUBE-sérumtriplecollagen.jpg",
    amazonUrl: "https://amzn.to/3MXfI0y",
    price: 16.73,
    rating: 4.6,
    reviews: 4100,
    description: "Triple complexe de Collagène (hydrolysé, marin et végétal) pour une action anti-âge complète. Repulpe, améliore l'élasticité et lisse le grain de peau. Texture fluide qui pénètre instantanément. Résultats visibles en 4 semaines. 55 ml.",
    applyTip: "Matin et soir après le nettoyage. Verser 2 à 3 gouttes dans le creux de la main, tapoter délicatement sur tout le visage et le cou en partant du centre vers l'extérieur. Ne pas frotter — laisser pénétrer avant la crème.",
    skinTypeTags: [],
    routineStep: "serum",
    isFeatured: false,
    active: true
  },
  {
    id: "m050",
    name: "Salmon DNA PDRN Pink Peptide Eye Serum",
    brand: "Medicube",
    category: "eye",
    imageUrl: "assets/MEDICUBE-contourdesyeux.jpg",
    amazonUrl: "https://amzn.to/4rsJbxx",
    price: 21.90,
    rating: 4.6,
    reviews: 3300,
    description: "Sérum yeux à l'ADN Saumon PDRN + Niacinamide + Rétinol pur. Réduit les rides fines, atténue les cernes et unifie le teint. Le PDRN stimule la régénération cellulaire tandis que le Rétinol densifie la peau fragile du contour des yeux. 1.01 fl.oz.",
    applyTip: "Matin et soir après le sérum visage. Déposer une micro-quantité avec l'annulaire et tapoter très délicatement de l'angle interne vers l'angle externe de l'œil, sur l'os orbitaire (jamais sur la paupière mobile). Ne jamais frotter.",
    skinTypeTags: [],
    routineStep: "eye",
    isFeatured: true,
    active: true
  },
  {
    id: "m051",
    name: "Collagen Glow Booster Milk Serum",
    brand: "Medicube",
    category: "serum",
    imageUrl: "assets/MEDICUBE-sérumbooster.jpg",
    amazonUrl: "https://amzn.to/4byHM3w",
    price: 22.96,
    rating: 4.6,
    reviews: 2700,
    description: "Sérum booster Twist & Click : Niacinamide + Protéines de Lait + Collagène Hydrolysé. Booste l'éclat, nourrit et renforce la barrière cutanée. Texture lait légère, absorption immédiate, aucun résidu. Idéal en cure d'éclat et d'hydratation.",
    applyTip: "Matin et soir, en toute première étape après le nettoyage. Tourner le flacon (Twist & Click) : une pression suffit pour le visage et le cou. Tapoter du bout des doigts jusqu'à absorption complète, puis enchaîne avec ton sérum ou ta crème.",
    skinTypeTags: [],
    routineStep: "serum",
    isFeatured: true,
    active: true
  },

  // ─── FOND DE TEINT ────────────────────────────────────────────
  {
    id: "m052",
    name: "Clinique Superbalanced Fond de Teint Liquide",
    brand: "Clinique",
    category: "foundation",
    imageUrl: "assets/CLINIQUE-fonddeteint.jpg",
    amazonUrl: "https://amzn.to/40rQLxq",
    price: 29.20,
    rating: 4.5,
    reviews: 3400,
    description: "Fond de teint liquide équilibre parfait — hydrate les zones sèches et contrôle le brillant sur les zones grasses. Formule dermatologiquement testée.",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },
  {
    id: "m053",
    name: "Wet n Wild Photo Focus Foundation Matte",
    brand: "Wet n Wild",
    category: "foundation",
    imageUrl: "assets/WETNWILD-fonddeteint.jpg",
    amazonUrl: "https://amzn.to/4uuWRuE",
    price: 9.99,
    rating: 4.3,
    reviews: 6200,
    description: "Fond de teint haute couverture avec complexe ajusteur de lumière. Finition mate, sans trace blanche, vegan. Dupe accessible du Clinique Superbalanced.",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },
  {
    id: "m054",
    name: "By Terry Hyaluronic Hydra-Foundation",
    brand: "By Terry",
    category: "foundation",
    imageUrl: "assets/BYTERRY-fonddeteintsoinspfhyaluronic.jpg",
    amazonUrl: "https://amzn.to/4bDoQk9",
    price: 18.83,
    rating: 4.4,
    reviews: 920,
    description: "Fond de teint soin à l'acide hyaluronique — couvrance modulable, fini naturel et hydratation longue durée. Teinte 200C.",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },
  {
    id: "m055",
    name: "Fond de Teint Coréen Stick 2 en 1 avec Pinceau Intégré",
    brand: "Cover",
    category: "foundation",
    imageUrl: "assets/COVER-fonddeteint.jpg",
    amazonUrl: "https://amzn.to/4s2XzO1",
    price: 11.97,
    rating: 4.2,
    reviews: 480,
    description: "Fond de teint stick coréen 2 en 1 avec pinceau intégré. S'adapte à la carnation, couvrance modulable, longue tenue résistant à l'eau. Teinte Medium.",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },
  {
    id: "m056",
    name: "NYX Make 'Em Wonder Fond de Teint 24h",
    brand: "NYX Professional Makeup",
    category: "foundation",
    imageUrl: "assets/NYX-Fonddeteint.jpg",
    amazonUrl: "https://amzn.to/4uxpNlQ",
    price: 14.19,
    rating: 4.4,
    reviews: 2100,
    description: "Fond de teint 24h sans effet plâtre à l'acide hyaluronique et extrait de guarana. Formule vegan. Teinte Natural. 30 ml.",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },
  {
    id: "m057",
    name: "Clinique Even Better Fond de Teint SPF 15 Vitamine C",
    brand: "Clinique",
    category: "foundation",
    imageUrl: "assets/CLINIQUE-fonddeteintSPF15.jpg",
    amazonUrl: "https://amzn.to/3Piq0c9",
    price: 22.08,
    rating: 4.6,
    reviews: 5100,
    description: "Fond de teint SPF 15 à la Vitamine C — couvrance moyenne, fini naturel. Unifie le teint et réduit les taches brunes sur le long terme.",
    badge: "vitc-spf",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: true,
    active: true
  },
  {
    id: "m058",
    name: "Charlotte Tilbury Flawless Filter Travel Size",
    brand: "Charlotte Tilbury",
    category: "foundation",
    imageUrl: "assets/CHARLOTTETILBURY-FDTtravelsize.jpg",
    amazonUrl: "https://amzn.to/4lt7LwS",
    price: 25.51,
    rating: 4.7,
    reviews: 3600,
    description: "Version voyage 5,5 ml du célèbre Flawless Filter — primer, highlighter et fond de teint en un. Teinte 2 Fair. Fini lumineux naturel.",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },
  {
    id: "m059",
    name: "Dermacol Mini Fond de Teint Mat Couverture Complète SPF30",
    brand: "Dermacol",
    category: "foundation",
    imageUrl: "assets/DERMACOL-fonddeteint.jpg",
    amazonUrl: "https://amzn.to/4dgETpl",
    price: 9.99,
    rating: 4.5,
    reviews: 8400,
    description: "Fond de teint mat SPF30 à couverture complète 13g — imperméable, longue durée. Idéal peaux grasses, acné et poches. Teinte 212.",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },

  // ─── CORRECTEUR / CC CRÈME (IT COSMETICS) ──────────────────────
  {
    id: "m060",
    name: "IT Cosmetics Do It All Concealer — Fair Warm",
    brand: "IT Cosmetics",
    category: "foundation",
    imageUrl: "assets/ITCOSMETIC-doitall-fairwarm.jpg",
    amazonUrl: "https://amzn.to/4sKi5D3",
    price: 35.00,
    rating: 4.5,
    reviews: 1600,
    description: "Correcteur + boosteur d'éclat longue durée, effet repulpant et anti-cernes. Formulé avec un sérum multivitaminé. Teinte Fair Warm. 7 ml.",
    badge: "vitc",
    pairedWith: "m068",
    skinTypeTags: [],
    routineStep: "foundation",
    concealerDepth: "clair",
    concealerTone: "warm",
    isFeatured: false,
    active: true
  },
  {
    id: "m061",
    name: "IT Cosmetics Do It All Concealer — Tan Neutral",
    brand: "IT Cosmetics",
    category: "foundation",
    imageUrl: "assets/ITCOSMETIC-doitall-tannatural.jpg",
    amazonUrl: "https://amzn.to/4uqCkXR",
    price: 35.00,
    rating: 4.5,
    reviews: 1600,
    description: "Correcteur + boosteur d'éclat longue durée, effet repulpant et anti-cernes. Formulé avec un sérum multivitaminé. Teinte Tan Neutral. 7 ml.",
    badge: "vitc",
    pairedWith: "m068",
    skinTypeTags: [],
    routineStep: "foundation",
    concealerDepth: "medium",
    concealerTone: "neutral",
    isFeatured: false,
    active: true
  },
  {
    id: "m062",
    name: "IT Cosmetics Do It All Concealer — Tan Rich Warm",
    brand: "IT Cosmetics",
    category: "foundation",
    imageUrl: "assets/ITCOSMETIC-doitall-tanrichwarm.jpg",
    amazonUrl: "https://amzn.to/4t3bwMb",
    price: 35.00,
    rating: 4.5,
    reviews: 1600,
    description: "Correcteur + boosteur d'éclat longue durée, effet repulpant et anti-cernes. Formulé avec un sérum multivitaminé. Teinte Tan Rich Warm. 7 ml.",
    badge: "vitc",
    pairedWith: "m068",
    skinTypeTags: [],
    routineStep: "foundation",
    concealerDepth: "fonce",
    concealerTone: "warm",
    isFeatured: false,
    active: true
  },
  {
    id: "m063",
    name: "IT Cosmetics CC+ Nude Glow SPF40 — Medium",
    brand: "IT Cosmetics",
    category: "foundation",
    imageUrl: "assets/ITCOSMETIC-CCCREmemedium.jpg",
    amazonUrl: "https://amzn.to/4scnKC2",
    price: 41.50,
    rating: 4.7,
    reviews: 8900,
    description: "CC crème SPF40 à couvrance moyenne — enrichie en peptides, collagène et vitamines. Fini naturel et lumineux. Teinte Medium. 32 ml.",
    badge: "vitc-spf",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: true,
    active: true
  },
  {
    id: "m064",
    name: "IT Cosmetics CC+ Nude Glow SPF40 — Medium Tan",
    brand: "IT Cosmetics",
    category: "foundation",
    imageUrl: "assets/ITCOSMETIC-CCCREmemediumtan.jpg",
    amazonUrl: "https://amzn.to/40uuQFH",
    price: 41.50,
    rating: 4.7,
    reviews: 8900,
    description: "CC crème SPF40 à couvrance moyenne — enrichie en peptides, collagène et vitamines. Fini naturel et lumineux. Teinte Medium Tan. 32 ml.",
    badge: "vitc-spf",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },
  {
    id: "m065",
    name: "IT Cosmetics CC+ Nude Glow SPF40 — Neutral Medium",
    brand: "IT Cosmetics",
    category: "foundation",
    imageUrl: "assets/ITCOSMETIC-CCcremeneutralmedium.jpg",
    amazonUrl: "https://amzn.to/4cGwtYf",
    price: 41.50,
    rating: 4.7,
    reviews: 8900,
    description: "CC crème SPF40 à couvrance moyenne — enrichie en peptides, collagène et vitamines. Fini naturel et lumineux. Teinte Neutral Medium. 32 ml.",
    badge: "vitc-spf",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },
  {
    id: "m066",
    name: "IT Cosmetics CC+ Nude Glow SPF40 — Neutral Tan",
    brand: "IT Cosmetics",
    category: "foundation",
    imageUrl: "assets/ITCOSMETIC-CCcremeneutraltan.jpg",
    amazonUrl: "https://amzn.to/46Vq6fX",
    price: 41.50,
    rating: 4.7,
    reviews: 8900,
    description: "CC crème SPF40 à couvrance moyenne — enrichie en peptides, collagène et vitamines. Fini naturel et lumineux. Teinte Neutral Tan. 32 ml.",
    badge: "vitc-spf",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },
  {
    id: "m067",
    name: "IT Cosmetics CC+ Nude Glow SPF40 — Fair Light",
    brand: "IT Cosmetics",
    category: "foundation",
    imageUrl: "assets/ITCOSMETIC-CCCREmefairlight.jpg",
    amazonUrl: "https://amzn.to/4utCnlN",
    price: 41.50,
    rating: 4.7,
    reviews: 8900,
    description: "CC crème SPF40 à couvrance moyenne — enrichie en peptides, collagène et vitamines. Fini naturel et lumineux. Teinte Fair Light. 32 ml.",
    badge: "vitc-spf",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },

  // ─── CHARLOTTE TILBURY ────────────────────────────────────────
  {
    id: "m069",
    name: "Pillow Talk Push Up Lashes Mascara — Travel 4 ml",
    brand: "Charlotte Tilbury",
    category: "mascara",
    imageUrl: "assets/CHARLOTTETILBURY-mascara1.jpg",
    amazonUrl: "https://amzn.to/4usLKSM",
    price: 22.00,
    rating: 4.4,
    reviews: 1800,
    description: "Mascara volume & recourbant de la collection Pillow Talk. Brosse en champignon pour soulever les cils à la racine, formule hydratante aux fibres de soie. Fini poupée très demandé. Format voyage 4 ml.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m070",
    name: "Hollywood Flawless Filter — Teinte 4.5 Medium, 30 ml",
    brand: "Charlotte Tilbury",
    category: "foundation",
    imageUrl: "assets/CHARLOTTETILBURY-flawlessfilter.jpg",
    amazonUrl: "https://amzn.to/4biZgzG",
    price: 39.00,
    rating: 4.6,
    reviews: 9200,
    description: "Complexion booster culte 3-en-1 : primer lumineux, highlighter et fond de teint léger. Floute les pores et imperfections, donne un fini lumière naturelle façon filtre photo. Teinte 4.5 Medium. 30 ml.",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },
  {
    id: "m071",
    name: "Charlotte's Magic Cream Healthy Glow, 50 ml",
    brand: "Charlotte Tilbury",
    category: "foundation",
    imageUrl: "assets/CHARLOTTETILBURY-BASEvisage.jpg",
    amazonUrl: "https://amzn.to/3Nr0WPA",
    price: 62.00,
    rating: 4.7,
    reviews: 14000,
    description: "Crème soin primée aux acides hyaluroniques, collagène et roses centifolia. Hydrate intensément, rebooste l'éclat et prépare le teint à accueillir le maquillage. Peut s'utiliser seule pour un effet peau nue lumineux, en été ou le matin pour un teint frais toute la journée.",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: true,
    active: true
  },
  {
    id: "m072",
    name: "Pillow Talk Lip Kit — Contour & Rouge à Lèvres",
    brand: "Charlotte Tilbury",
    category: "lipstick",
    imageUrl: "assets/CHARLOTTETILBURY-pillowtalkcoffret.jpg",
    amazonUrl: "https://amzn.to/4rwuLMP",
    price: 32.00,
    rating: 4.8,
    reviews: 6400,
    description: "Coffret duo iconique Pillow Talk : 1 crayon contour lèvres + 1 rouge à lèvres satiné. Teinte nude rosé intemporelle, la plus vendue de Charlotte Tilbury. Format voyage parfait pour un look lèvres parfaites en un geste.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m073",
    name: "Legendary Lashes Volume 2 Mascara Noir, 8 ml",
    brand: "Charlotte Tilbury",
    category: "mascara",
    imageUrl: "assets/CHARLOTTETILBURY-mascara2.jpg",
    amazonUrl: "https://amzn.to/4sBTUXg",
    price: 30.00,
    rating: 4.5,
    reviews: 3700,
    description: "Mascara volumateur extrême — jusqu'à 8x plus de volume en un seul passage. Brosse XXL à tige flexible pour attraper chaque cil. Formule buildable, résistante à l'humidité, longue tenue intense. 8 ml.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: true,
    active: true
  },
  {
    id: "m074",
    name: "Magic Away Correcteur Liquide — Teinte 03, 4 ml",
    brand: "Charlotte Tilbury",
    category: "foundation",
    imageUrl: "assets/CHARLOTTETILBURY-correcteur.jpg",
    amazonUrl: "https://amzn.to/4sJ8UTp",
    price: 30.00,
    rating: 4.5,
    reviews: 2900,
    description: "Correcteur liquide haute couverture, léger comme une seconde peau. Complexe Vitamin Boost + actifs hydratants pour couvrir cernes et imperfections sans effet masque. Fini naturel longue tenue. Teinte 03. 4 ml.",
    skinTypeTags: [],
    routineStep: "foundation",
    concealerDepth: "clair",
    concealerTone: "neutral",
    isFeatured: false,
    active: true
  },

  // ─── BRONZERS & BONNE MINE ────────────────────────────────────
  {
    id: "m075",
    name: "Sun Lover Glow Poudre Bronzante — 010 Sun Kissed Bronze",
    brand: "Catrice",
    category: "bronzer",
    imageUrl: "assets/SUNLOVER-POUDRE.jpg",
    amazonUrl: "https://amzn.to/4bLHqFZ",
    price: 6.99,
    rating: 4.3,
    reviews: 3200,
    description: "Poudre bronzante illuminatrice à effet bonne mine. Teinte universelle 010 Sun Kissed Bronze — donne un hâle naturel et lumineux. Formule légère, fondante, longue tenue. Idéale seule ou sur fond de teint.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m076",
    name: "Sunkissed Bronzing Serum — Effet Bonne Mine",
    brand: "Weleda",
    category: "bronzer",
    imageUrl: "assets/WELEDA-SERUMbronzer.jpg",
    amazonUrl: "https://amzn.to/4bLHqFZ",
    price: 24.90,
    rating: 4.4,
    reviews: 980,
    description: "Sérum bronzant naturel certifié NATRUE — formule légère qui donne un hâle personnalisé et lumineux. Enrichi en actifs botaniques bio. S'utilise seul ou mélangé à sa crème de jour.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m077",
    name: "Sunkissed Bronzing Serum — Glow Personnalisé",
    brand: "Weleda",
    category: "bronzer",
    imageUrl: "assets/WELEDA-SERUMGlow.jpg",
    amazonUrl: "https://amzn.to/47uh4GU",
    price: 24.90,
    rating: 4.5,
    reviews: 1100,
    description: "Sérum glow bronzant certifié NATRUE — couvrance transparente à légère pour un effet bonne mine instantané. Unifie le teint sans le masquer, donne un aspect bronzé naturel. Formule non grasse, teinte universelle toutes carnations.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m078",
    name: "Sunkissed Bronzing Serum — Pore Refining",
    brand: "Weleda",
    category: "bronzer",
    imageUrl: "assets/WELEDA-SERUMporerefining.jpg",
    amazonUrl: "https://amzn.to/4lv6VzN",
    price: 24.90,
    rating: 4.4,
    reviews: 870,
    description: "Sérum bronzant affinant les pores certifié NATRUE — lisse le grain de peau tout en apportant un hâle naturel et lumineux. Formule légère, actifs botaniques bio. Fini peau nue parfaite.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m079",
    name: "Buttermelt Bronzer Crème — Serve Butta",
    brand: "NYX Professional Makeup",
    category: "bronzer",
    imageUrl: "assets/NYX-bronzercrèmedesservebutta.jpg",
    amazonUrl: "https://amzn.to/3Nr4n8W",
    price: 14.99,
    rating: 4.4,
    reviews: 2600,
    description: "Bronzer crème fondant texture beurre ultra-soyeuse. Teinte Serve Butta — chaleur dorée naturelle. S'applique du bout des doigts pour un hâle frais et lumineux. Formule vegan longue tenue.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m080",
    name: "Sun Kissed Drops Gel Bronzant Liquide",
    brand: "Clinique",
    category: "bronzer",
    imageUrl: "assets/CLINIQUE-sunkissed.jpg",
    amazonUrl: "https://amzn.to/3P45iNi",
    price: 31.33,
    rating: 4.5,
    reviews: 3800,
    description: "Gel bronzant liquide effet hâle doré naturel — retour de vacances instantané. Teinte universelle non grasse, fini mat. A mélanger à sa crème de jour ou SPF pour un hâle léger, ou à appliquer pur pour un bronze plus intense. Fondé sur la science dermatologique Clinique.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: true,
    active: true
  },

  // ─── CLINIQUE — NETTOYANT & FOND DE TEINT POUDRE ──────────────
  {
    id: "m081",
    name: "Take The Day Off Cleansing Balm",
    brand: "Clinique",
    category: "cleanser",
    imageUrl: "assets/CLINIQUE-takethedayoff.jpg",
    amazonUrl: "https://amzn.to/4rtqKbM",
    price: 32.00,
    rating: 4.7,
    reviews: 18000,
    description: "Baume démaquillant culte — fond au contact de l'eau pour dissoudre le maquillage waterproof, le SPF et les impuretés sans laisser de résidu gras. Convient aux yeux sensibles et aux lentilles. Laisse la peau propre, douce et confortable.",
    skinTypeTags: [],
    routineStep: "cleanser",
    isFeatured: true,
    active: true
  },
  {
    id: "m082",
    name: "Superpowder Double Face Powder — Matte Beige",
    brand: "Clinique",
    category: "foundation",
    imageUrl: "assets/CLINIQUE-fonddeteintpoudre1.jpg",
    amazonUrl: "https://amzn.to/40z16Yi",
    price: 32.00,
    rating: 4.5,
    reviews: 4200,
    description: "Fond de teint poudre double effet — s'utilise sec comme poudre de finition ou humide comme fond de teint couvrance moyenne. Formule matifiante longue tenue. Teinte Matte Beige.",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },
  {
    id: "m083",
    name: "Superpowder Double Face Powder — Matt Honey",
    brand: "Clinique",
    category: "foundation",
    imageUrl: "assets/CLINIQUE-fonddeteintpoudremattehoney.jpg",
    amazonUrl: "https://amzn.to/46XPwcX",
    price: 32.00,
    rating: 4.5,
    reviews: 4200,
    description: "Fond de teint poudre double effet — s'utilise sec comme poudre de finition ou humide comme fond de teint couvrance moyenne. Formule matifiante longue tenue. Teinte Matt Honey.",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  },

  // ─── CLINIQUE — LÈVRES ─────────────────────────────────────────
  {
    id: "m084",
    name: "Almost Lipstick Baume Teinté — Rose",
    brand: "Clinique",
    category: "lipbalm",
    imageUrl: "assets/CLINIQUE-baumeàlèvresrose.jpg",
    amazonUrl: "https://amzn.to/46V3Djg",
    price: 23.00,
    rating: 4.7,
    reviews: 5600,
    description: "Baume à lèvres teinté rose — hydratation intense et couleur subtile buildable. Formule nourrissante à la vitamine E et beurre de karité. Parfait pour un look naturel ou un maquillage lèvres discret toute la journée.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: true,
    active: true
  },
  {
    id: "m085",
    name: "Quickliner for Lips Intense — Intense Blush",
    brand: "Clinique",
    category: "lipstick",
    imageUrl: "assets/CLINIQUE-crayonàlèvresintenseblush.jpg",
    amazonUrl: "https://amzn.to/4bDpXjX",
    price: 22.00,
    rating: 4.6,
    reviews: 2100,
    description: "Crayon contour lèvres longue tenue Intense Blush — teinte rose vif intense. Ne se taille pas, formule non desséchante. Définit et structure les lèvres avec précision pour un résultat impeccable toute la journée.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: true,
    active: true
  },
  {
    id: "m086",
    name: "Quickliner for Lips Intense — Crushberry",
    brand: "Clinique",
    category: "lipstick",
    imageUrl: "assets/CLINIQUE-crayonàlèvrescrushberry.jpg",
    amazonUrl: "https://amzn.to/4usJOd4",
    price: 22.00,
    rating: 4.6,
    reviews: 2100,
    description: "Crayon contour lèvres longue tenue Crushberry — teinte bordeaux-prune profonde. Ne se taille pas, formule non desséchante. Définit et structure les lèvres avec précision pour un résultat impeccable toute la journée.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m087",
    name: "Quickliner for Lips Intense — Intense Cayenne",
    brand: "Clinique",
    category: "lipstick",
    imageUrl: "assets/CLINIQUE-crayonàlèvresintensecayenne.jpg",
    amazonUrl: "https://amzn.to/4bGHWG9",
    price: 22.00,
    rating: 4.6,
    reviews: 2100,
    description: "Crayon contour lèvres longue tenue Intense Cayenne — teinte rouge orangé épicé. Ne se taille pas, formule non desséchante. Définit et structure les lèvres avec précision pour un résultat impeccable toute la journée.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m088",
    name: "Chubby Stick Tinted Lip Color Balm",
    brand: "Clinique",
    category: "lipbalm",
    imageUrl: "assets/CLINIQUE-chubbystick.jpg",
    amazonUrl: "https://amzn.to/4lp4pe6",
    price: 26.00,
    rating: 4.6,
    reviews: 7400,
    description: "Baume à lèvres teinté format jumbo — hydratation intense au beurre de mangue et huile de jojoba, couleur modulable. Texture balm fondante, confort toute la journée. Convient aux lèvres sèches. 3 g.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },

  // ─── ELIZABETH ARDEN — LÈVRES ─────────────────────────────────
  {
    id: "m089",
    name: "Eight Hour Cream Lip Protectant Sheer Tint — Plum",
    brand: "Elizabeth Arden",
    category: "lipbalm",
    imageUrl: "assets/ELIZABETHARDEN-BAUMEALEVRESPLUM.jpg",
    amazonUrl: "https://amzn.to/3P5C94i",
    price: 22.00,
    rating: 4.7,
    reviews: 6800,
    description: "Baume à lèvres teinté culte teinte Plum — teinte prune très légère et naturelle qui se révèle et s'intensifie au fil des applications. Repasser 2 à 3 fois pour accentuer la couleur. Hydrate, protège et adoucit durablement. Formule iconique aux acides gras et Vitamine E.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: true,
    active: true
  },
  {
    id: "m090",
    name: "Eight Hour Cream Lip Protectant Sheer Tint — Honey",
    brand: "Elizabeth Arden",
    category: "lipbalm",
    imageUrl: "assets/ELIZABETHARDEN-BAUMEALEVRESHONEY.jpg",
    amazonUrl: "https://amzn.to/4utHLVY",
    price: 22.00,
    rating: 4.7,
    reviews: 6800,
    description: "Baume à lèvres teinté culte teinte Honey — teinte miel dorée lumineuse, très légère et buildable. Repasser 2 à 3 fois pour accentuer la couleur. Hydrate, protège et adoucit durablement. Formule iconique aux acides gras et Vitamine E.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },

  // ─── MASCARAS ─────────────────────────────────────────────────
  {
    id: "m091",
    name: "High Impact Mascara — Noir",
    brand: "Clinique",
    category: "mascara",
    imageUrl: "assets/CLINIQUE-mascara1.jpg",
    amazonUrl: "https://amzn.to/4bLKLVx",
    price: 26.00,
    rating: 4.5,
    reviews: 5800,
    description: "Mascara volume intense — brosse large pour un maximum de volume sans paquets. Formule ophthalmologiquement testée, convient aux yeux sensibles et porteurs de lentilles. Tenue longue durée. Teinte Noir.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m092",
    name: "High Impact Mascara — Brown",
    brand: "Clinique",
    category: "mascara",
    imageUrl: "assets/CLINIQUE-mascara1brown.jpg",
    amazonUrl: "https://amzn.to/4uq5Jl0",
    price: 26.00,
    rating: 4.5,
    reviews: 3200,
    description: "Mascara volume intense — même formule ophthalmologiquement testée que le High Impact, dans une teinte brun plus naturelle. Idéal pour un regard doux et définition subtile. Convient aux yeux sensibles.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m093",
    name: "Sky High Mascara Longueur Waterproof",
    brand: "Maybelline New York",
    category: "mascara",
    imageUrl: "assets/MAYBELLINE-mascaraSKY.jpg",
    amazonUrl: "https://amzn.to/3PhA7hq",
    price: 13.99,
    rating: 4.5,
    reviews: 28000,
    description: "Mascara allongeant waterproof viral — brosse flexible pour atteindre chaque cil jusqu'aux coins. Formule enrichie en huile d'argan et bambou. Fini intense longue tenue toute la journée, résiste à l'eau.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: true,
    active: true
  },
  {
    id: "m094",
    name: "Mascara Volumateur Anti-Paquets Anti-Bavures",
    brand: "Clinique",
    category: "mascara",
    imageUrl: "assets/CLINIQUE-mascara2.jpg",
    amazonUrl: "https://amzn.to/4rtyCtS",
    price: 30.00,
    rating: 4.4,
    reviews: 2100,
    description: "Mascara volume intelligent — formule anti-paquets et anti-bavures pour des cils pleins et séparés. Convient aux yeux sensibles et aux porteurs de lentilles. Tenue impeccable toute la journée.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m095",
    name: "Superhero Elastic Stretch Volumizing Mascara",
    brand: "IT Cosmetics",
    category: "mascara",
    imageUrl: "assets/ITCOSMETIC-mascara1.jpg",
    amazonUrl: "https://amzn.to/4uKU54H",
    price: 30.00,
    rating: 4.5,
    reviews: 4600,
    description: "Mascara volumateur extensible — formule élastique qui s'étire pour allonger et gainer chaque cil. Infusé en kératine, biotine et collagène. Volume intense buildable, résistant à l'humidité, sans paquets.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m096",
    name: "Mascara Allongement Waterproof — Yeux Sensibles",
    brand: "3ina",
    category: "mascara",
    imageUrl: "assets/MINA-Mascara1.jpg",
    amazonUrl: "https://amzn.to/4cFzwzU",
    price: 16.99,
    rating: 4.3,
    reviews: 1400,
    description: "Mascara allongeant waterproof de la marque 3ina — formule douce spécialement conçue pour les yeux sensibles. Brosse peigne pour une séparation parfaite et un fini allongé naturel. Tenue longue durée.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m097",
    name: "Double-Ended Lash Primer + Mascara 2-en-1",
    brand: "RevitaLash",
    category: "mascara",
    imageUrl: "assets/REVITALASH-Mascara.jpg",
    amazonUrl: "https://amzn.to/410Fnsn",
    price: 42.00,
    rating: 4.6,
    reviews: 3200,
    description: "Système 2-en-1 professionnel : primer bleu d'un côté qui prépare, sépare et amplifie l'adhérence des cils, mascara noir de l'autre pour volume et couleur intenses. Chaque cil traité individuellement, zéro paquets. Waterproof longue tenue, volume constructible.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: true,
    active: true
  },

  // ─── ROUGES À LÈVRES ─────────────────────────────────────────
  {
    id: "m098",
    name: "Long Last Soft Matte Lipstick",
    brand: "Clinique",
    category: "lipstick",
    imageUrl: "assets/CLINIQUE-rougeàlèvres.jpg",
    amazonUrl: "https://amzn.to/4b5NKsE",
    price: 28.00,
    rating: 4.5,
    reviews: 2400,
    description: "Rouge à lèvres longue tenue fini satiné — formule hydratante qui tient jusqu'à 10 heures sans dessécher. Couleur intense buildable, confort toute la journée. Ophthalmologiquement testé, convient aux yeux sensibles.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m099",
    name: "Unlimited Stylo Rouge à Lèvres Crémeux 10h",
    brand: "KIKO Milano",
    category: "lipstick",
    imageUrl: "assets/KIKOMILANO-ROUGEàlèvres1.jpg",
    amazonUrl: "https://amzn.to/3NDD9w1",
    price: 12.99,
    rating: 4.4,
    reviews: 3800,
    description: "Rouge à lèvres crémeux ultra-pigmenté longue tenue 10 heures — texture onctueuse qui glisse sans tirer. Couvre en un seul passage, sans transfert. Résistant à l'eau, sans dessèchement des lèvres.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m100",
    name: "Gossamer Emotion Lipstick Onctueux — 142 Deep Mauve",
    brand: "KIKO Milano",
    category: "lipstick",
    imageUrl: "assets/KIKOMILANO-ROUGEàlèvres2.jpg",
    amazonUrl: "https://amzn.to/4t3BqPV",
    price: 11.99,
    rating: 4.4,
    reviews: 2100,
    description: "Rouge à lèvres onctueux fini satiné — teinte 142 Deep Mauve, violet-prune profond et élégant. Formule enrichie en huiles nourrissantes pour un confort longue durée. Couvrance modulable, lèvres hydratées et pulpeuses.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },
  {
    id: "m101",
    name: "Gossamer Emotion Lipstick Onctueux — 138 Red Amber",
    brand: "KIKO Milano",
    category: "lipstick",
    imageUrl: "assets/KIKOMILANO-ROUGEàlèvres3.jpg",
    amazonUrl: "https://amzn.to/4s9sg4h",
    price: 11.99,
    rating: 4.4,
    reviews: 2100,
    description: "Rouge à lèvres onctueux fini satiné — teinte 138 Red Amber, rouge orangé chaud et lumineux. Formule enrichie en huiles nourrissantes pour un confort longue durée. Couvrance modulable, lèvres hydratées et pulpeuses.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: false,
    active: true
  },

  // ─── NOUVEAUX PRODUITS EN VEDETTE ──────────────────────────────
  {
    id: "m102",
    name: "Age-R Booster Masque de Nuit Lifting",
    brand: "MEDICUBE",
    category: "nightmask",
    imageUrl: "assets/MEDICUBE-masquenuit.jpg",
    amazonUrl: "https://amzn.to/4d77u0z",
    price: 32.90,
    rating: 4.6,
    reviews: 8200,
    description: "Masque de nuit lissant et repulpant — actifs fermeté (collagène, peptides) qui agissent pendant le sommeil. Texture gel enveloppante, se rince au réveil. Peau rebondie, rides atténuées, effet lifting visible dès la première nuit.",
    skinTypeTags: [],
    routineStep: "soir",
    isFeatured: true,
    active: true
  },
  {
    id: "m103",
    name: "Stay-N Lipliner Waterproof Longue Tenue",
    brand: "SACHEU",
    category: "lipstick",
    imageUrl: "assets/SACHEU-Lipliner.jpg",
    amazonUrl: "https://amzn.to/4uluGhw",
    price: 18.90,
    rating: 4.5,
    reviews: 5400,
    description: "Lipliner waterproof ultra-précis — formule longue tenue qui contourne, structure et agrandit le galbe des lèvres. Texture crémeuse qui ne bave pas ni ne migre. Compatible avec tous les rouges à lèvres. Indispensable pour un maquillage lèvres net.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: true,
    active: true
  },
  {
    id: "m104",
    name: "Lip Butter Balm — Coquelicot",
    brand: "Summer Fridays",
    category: "lipbalm",
    shadeName: "Coquelicot",
    colorHex: "#C0392B",
    imageUrl: "assets/SUMMERFRIDAYS-LIPS-coquelicot.jpg",
    amazonUrl: "https://amzn.to/4bdxndy",
    price: 50.00,
    rating: 4.7,
    reviews: 12000,
    description: "Baume à lèvres nourrissant teinté — teinte Coquelicot, rouge vif inspiré des champs de fleurs. Formule au beurre de shea, à la vanille et aux extraits de framboise. Hydrate et embellit les lèvres avec un fini glossy naturel. Couvrance buildable.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: true,
    active: true
  },
  {
    id: "m105",
    name: "Lip Butter Balm — Brown Sugar",
    brand: "Summer Fridays",
    category: "lipbalm",
    shadeName: "Brown Sugar",
    colorHex: "#7B4F2E",
    imageUrl: "assets/SUMMERFRIDAYS-LIPS-sucrebrun.jpg",
    amazonUrl: "https://amzn.to/3P1slZb",
    price: 50.00,
    rating: 4.7,
    reviews: 12000,
    description: "Baume à lèvres nourrissant teinté — teinte Brown Sugar, brun chaud et caramel ultra-flatteur. Formule au beurre de shea, à la vanille et aux extraits de framboise. Hydrate et embellit les lèvres avec un fini glossy naturel. Couvrance buildable.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: true,
    active: true
  },
  {
    id: "m106",
    name: "Lip Butter Balm — Pink Sugar",
    brand: "Summer Fridays",
    category: "lipbalm",
    shadeName: "Pink Sugar",
    colorHex: "#E8A0A8",
    imageUrl: "assets/SUMMERFRIDAYS-LIPS-pinksugar.jpg",
    amazonUrl: "https://amzn.to/4d7byhl",
    price: 50.00,
    rating: 4.7,
    reviews: 12000,
    description: "Baume à lèvres nourrissant teinté — teinte Pink Sugar, rose poudrée romantique et lumineuse. Formule au beurre de shea, à la vanille et aux extraits de framboise. Hydrate et embellit les lèvres avec un fini glossy naturel. Couvrance buildable.",
    skinTypeTags: [],
    routineStep: "makeup",
    isFeatured: true,
    active: true
  },
  {
    id: "m107",
    name: "Relief Sun Rice + Probiotics SPF50+",
    brand: "Beauty of Joseon",
    category: "spf",
    imageUrl: "assets/Beautyofjoseon-SPF50.jpg",
    amazonUrl: "https://amzn.to/4us6Vo4",
    price: 16.90,
    rating: 4.8,
    reviews: 42000,
    description: "Crème solaire coréenne culte SPF50+ PA++++ — formule légère enrichie en eau de riz et probiotiques qui hydrate, protège et illumine sans effet blanc. Texture fondante, fini satiné naturel. La référence pour protéger et unifier le teint au quotidien.",
    skinTypeTags: ["normale", "mixte", "sèche", "sensible"],
    badge: "vitc-spf",
    routineStep: "matin",
    isFeatured: true,
    active: true
  },
  {
    id: "m108",
    name: "Heartleaf Niacinamide 10% Sérum Pores & Éclat",
    brand: "ANUA",
    category: "serum",
    imageUrl: "assets/ANUA-Sérumniaciamide.jpg",
    amazonUrl: "https://amzn.to/4bJQT1u",
    price: 22.90,
    rating: 4.7,
    reviews: 18500,
    description: "Sérum niacinamide 10% à la feuille de Heartleaf — resserre les pores, régule le sébum, atténue les taches et rougeurs. Enrichi en extrait de centella asiatica pour apaiser les peaux réactives. Texture légère, absorbe en quelques secondes.",
    skinTypeTags: ["grasse", "mixte"],
    badge: "h2o",
    routineStep: "matin",
    isFeatured: true,
    active: true
  },

  {
    id: "m109",
    name: "Anthelios UV-Mune 400 Crème Hydratante SPF50+",
    brand: "LA ROCHE-POSAY",
    category: "spf",
    imageUrl: "assets/LAROCHEPOSAY-cr\u00e8mevisageSPF.jpg",
    amazonUrl: "https://amzn.to/41aMKgS",
    price: 30.00,
    rating: 4.6,
    reviews: 12400,
    description: "Crème solaire visage SPF50+ ultra-légère, formule sans parfum adaptée aux peaux sensibles. Filtre UVA-PF 80 pour une protection longue durée. Texture fondante non grasse, idéale sous le maquillage. Testée sous contrôle dermatologique.",
    skinTypeTags: ["sensible", "normale", "mixte", "sèche"],
    badge: "spf",
    routineStep: "matin",
    isFeatured: true,
    active: true
  },
  {
    id: "m110",
    name: "Crème Visage Ultrasensitive Non Parfumée",
    brand: "EUCERIN",
    category: "soin",
    imageUrl: "assets/EUCERIN-Ultrasensitive.jpg",
    amazonUrl: "https://amzn.to/47U9Gor",
    price: 19.90,
    rating: 4.5,
    reviews: 8700,
    description: "Crème hydratante visage formulée pour les peaux ultra-sensibles et réactives. Sans parfum, sans colorant, enrichie en licochalcone A pour apaiser les rougeurs. Texture légère qui pénètre rapidement sans résidu gras. Testée sous contrôle dermatologique.",
    skinTypeTags: ["sensible", "normale", "sèche"],
    badge: null,
    routineStep: "matin",
    isFeatured: true,
    active: true
  },
  {
    id: "m111",
    name: "Photoderm SPF50+ Crème Légère",
    brand: "BIODERMA",
    category: "spf",
    imageUrl: "assets/BIODERMA-SPF50.jpg",
    amazonUrl: "https://amzn.to/4sljFvp",
    price: 17.39,
    rating: 4.5,
    reviews: 9300,
    description: "Protection solaire SPF50+ à texture légère pour le visage. Formule brevetée Cellular Bioprotection — protège l'ADN des cellules cutanées contre les UVA/UVB. Fini mat, non comédogène, convient aux peaux mixtes à grasses. Résiste à la transpiration.",
    skinTypeTags: ["mixte", "grasse", "normale"],
    badge: "spf",
    routineStep: "matin",
    isFeatured: true,
    active: true
  },

  // ─── ACCESSOIRES MAKEUP ────────────────────────────────────────
  {
    id: "m068",
    name: "Pinceau Correcteur & Fond de Teint 270S",
    brand: "Energy",
    category: "accessoire",
    imageUrl: "assets/ENERGY 270S-Pinceau.jpg",
    amazonUrl: "https://amzn.to/4cLwBWm",
    price: 6.99,
    rating: 4.4,
    reviews: 2100,
    description: "Pinceau plat biseauté 270S — idéal pour étaler et estomper le correcteur ou le fond de teint liquide. Poils synthétiques ultra-doux, prise en main ergonomique.",
    skinTypeTags: [],
    routineStep: "foundation",
    isFeatured: false,
    active: true
  }

];
